### ISSUE TITLE
2.14 breaking change: parsing xml string as JsonNode/Object used to return just a String, now returns an Object/Map

### ISSUE THREAD

**Issue by jeronimonunes** [FasterXML/jackson-dataformat-xml#587] opened 2023-03-21 21:41 UTC
Breaking change in my application when upgrading from 2.13.5 to 2.14

xmlMapper.readValue(xmlStreamReader, JsonNode.class)

with string 

```xml
<tag>13,2</tag>
```

 used to return "13,2". Now it returns a map {"": "13,2"}

Same thing happens if I use xmlMapper.readValue(xmlStreamReader, Object.class)

**Comment by cowtowncoder** [comment] 2023-03-21 22:42
I would need actual reproduction: string `"13,2"` is not valid XML so I'd need to know actual input in question.

I don't doubt there may be a change (this is likely for improved handling of `JsonNode` as target, to allow handling of duplicate elements), just need to know what exactly is being attempte.

**Comment by jeronimonunes** [comment] 2023-03-22 08:08
Sorry, I should have written the whole xml in the description.
About the example above, same thing happens if I try to pass Object.class to readValue. It used to return a String, now it returns a Map.

**Comment by cowtowncoder** [comment] 2023-03-24 01:53
Ok. This is an ambiguous case since:

```xml
<value>abc</value>
```

could express JSON equivalents of

```
{ "value" : "abc" }
```

or 

```
"abc"
```

And for most users former is probably more likely to be what they want.
But with `java.lang.Object` there's no resolving that ambiguity.

From practical perspective, yes, this is breaking change for your use case.
But it is also behavior that Jackson 2.14 and later will go with.

To read that value as a `String` you would need to use target type of `String.class`.

**Comment by cowtowncoder** [comment] 2023-03-24 01:56
Hmmh. Ok, I wrote first answer, saying this is expected... but then started thinking description was not correct.

What I do think is happening is that the change is due to improved handling of root level POJOs; and related to ambiguity of `java.lang.Object` as target; for which both `Map` and `String` are legal... and where with XML there is bit of natural ambiguity.

I suspect that the new behavior is what we will be going with, for what that is worth.

But I think that target type of `String.class` would give you the old behavior.

**Comment by jeronimonunes** [comment] 2023-03-24 07:16
It does. I was first decoding everything to JsonNode and later using treeToValue to convert to other types.

Maybe Jackson can see that "" -> "ABC" is not a legal map because it only have "" as key and then return only the value?

**Comment by jeronimonunes** [comment] 2023-03-24 07:21
I'm handling huge xmls and was keeping a temporary JsonNode before converting to the final type so I could log the content of that tag if the conversation failed. Do you know another temporary object I can use to store a single Xml tag for later conversion?

**Comment by cowtowncoder** [comment] 2023-03-24 16:37
Empty String ("") is a valid JSON key.

Unfortunately buffering by Jackson uses `TokenBuffer`, which retains only converted `JsonToken`s, not the underlying XML contents.

I would have recommended trying `JsonNode`, but it probably has similar behavior.
I cannot think of anything that would safely buffer everything without transformation, unfortunately.

It may be necessary to do buffering at lower level (`Reader` or `InputStream` used), and use that for diagnostics on failure: `JsonFactory` (or `XmlFactory` subtype) has method

    public JsonFactory setInputDecorator(InputDecorator d)

that may make this approach simpler (although if you control caller you can just wrap `Reader` / `InputStream` on your own).

**Comment by patryk-wojcik-db** [comment] 2024-01-30 11:39
I can confirm that updating from 2.13.3 to 2.14.x or higher introduces breaking change.

```
    @Test //This test is going to fail if com.fasterxml.jackson.dataformat.jackson-dataformat-xml is updated to 2.14.x or higher due to breaking change introduced in jackson-dataformat-xml 2.14
    void testTextNode() throws IOException {
        String exampleXml = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<text>Hello World</text>\n</xml>";

        XMLInputFactory input = new WstxInputFactory();
        input.setProperty(XMLInputFactory.IS_NAMESPACE_AWARE, Boolean.FALSE);

        JsonNode rootNode = new XmlMapper(new XmlFactory(input, new WstxOutputFactory())).readTree(
                exampleXml.getBytes());
        
        Assertions.assertAll(
                () -> Assertions.assertTrue(rootNode.isTextual()),
                () -> Assertions.assertEquals("Hello World", rootNode.textValue()));
    }
```
Above test passes for jackson-dataformat-xml 2.13.3:
![image](https://github.com/FasterXML/jackson-dataformat-xml/assets/91190502/b38b251f-d786-48bb-8ba5-5d61f91678ed)

 and fails for any version above that due to difference in node handling:
![image](https://github.com/FasterXML/jackson-dataformat-xml/assets/91190502/a55478ba-ee5a-4c09-b5bb-1d44e10ef02b)

**Comment by cowtowncoder** [comment] 2024-01-31 03:57
New behavior -- binding as `ObjectNode` (for target type of `JsonNode`) and `Map` (target type of `java.lang.Object`) -- is considered correct and expected behavior for Jackson. 
Will close the issue.

That said, I would be open to idea of having configuration option to allow alternate handling, if anyone wants to try creating a PR (if so, it'd be `FromXmlParser.Feature`)

**Closed by cowtowncoder** 2024-01-31 03:57 UTC
Labels: has-failing-test
