### ISSUE TITLE
Jackson deserializer not using JacksonXmlProperty localname when used with JsonPOJOBuilder

### ISSUE THREAD

**Issue by Bokoblin** [FasterXML/jackson-dataformat-xml#384] opened 2020-02-26 10:36 UTC
Hello,

I'm currently developing a library to enable conversion between MSML with custom elements and Java's POJOs. I have encountered several issues related to jackson (de)serialization in the last few weeks needing workarounds that I would prefer to avoid.
I have already dug over issues there and tentative solutions before posting here.

This issue report concerns the **JacksonXmlProperty** annotation's **localname** not used by Jackson Deserializer when **JsonPOJOBuilder** is also used.
Ideally, jackson should be aware of the local name specified by this annotation when deserializing with the pojo builder annotation also used.

This issue occurs to me on the following code:
```
@Builder
@JacksonXmlRootElement(localName = "stats")
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonDeserialize(builder = StatsQuery.StatsQueryBuilder.class)
public class StatsQuery {
    @JacksonXmlProperty(localName = "queryid", isAttribute = true)
    private String queryId;

    @JacksonXmlProperty(localName = "list", isAttribute = true)
    private String list;

    @JacksonXmlProperty(localName = "reset", isAttribute = true)
    @Builder.Default private Boolean reset = true;

    @JsonPOJOBuilder(withPrefix = "")
    public static class StatsQueryBuilder {
    }
}
```

You can see there that the java field is using camelCase per conventions and the xml property are defined in downcase.
The builder class need to be specified so I can have **reset** value set to true and not null as I use Lombok as a builder generator

Attempting a deserialization with the above code results in the following exception:
``com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "queryid" (class StatsQuery$StatsQueryBuilder), not marked as ignorable (3 known properties: "queryId", "list", "reset"])``.

The problem seems to be that in this case of having **@JsonPOJOBuilder**, jackson uses java field names and not **@JacksonXMLProperty** as it should. This occurs for every fields of my project when the java name is different (or has a different case) than the property, which is the goal of having a local name attribute.

The temporary solution, I have found was to also set the JAXB annotation **@JsonProperty("queryid")** on the field.
However you can easily see that mentioning 2 annotations with the same supposed goal is not a proper way of writing good code as the two annotations are coupled (modifying one causes modifying the other).

If you need more information, please tell me.

System information
---
Java version : 11
Jackson version : jackson-dataformat-xml@2.10.2
Woodstox : woodstox-core@6.0.3
Lombok : lombok@1.18.12

**Comment by cowtowncoder** [comment] 2020-02-26 18:56
One quick question: does use of `@Builder` suggest use of Lombok? If so, a reproduction would need processed sources, to see what is actually being used. We do not allow use of Lombok as a dependency even for tests (due to that breaking ability to just d/l project and build without changes to classpath). It is likely that simple translation would work to reproduce the issue, but there are some cases where Lombok configuration has effect on this working.

**Comment by Bokoblin** [comment] 2020-02-27 12:37
Yeah @Builder implies using lombok.
What would you need exactly to reproduce the issue?

**Comment by cowtowncoder** [comment] 2020-02-29 00:29
@Bokoblin just the class definition as processed by Lombok, that is; instead of Lombok annotations (to generate actual bytecode), definition that in plain JDK java (and Jackson of course) reproducing the problem. I think Lombok does (optionally?) produce .java definitions that get compiled, as part of build.

**Comment by Bokoblin** [comment] 2020-02-29 01:55
Okay, I see, I can get the .class decompiled and the test case I use for
you to try.
I'll send you that on Monday

Le sam. 29 févr. 2020 à 01:29, Tatu Saloranta <notifications@github.com> a
écrit :

**Comment by cowtowncoder** [comment] 2020-03-02 02:19
@Bokoblin I was hoping there was a way to instruct Lombok to write out generated code, but maybe such a feature does not exist. However, what seems to be possible is to use IntelliJ (if that is IDE you use, or have access to) to have a look: this probably does use decompiler but might be easier to access and maybe have more information.
Either way thank you for helping troubleshoot the problem!

**Comment by Bokoblin** [comment] 2020-03-03 09:31
Yeah, I know of IntelliJ decompiler and used it. 
I have prepared you a zip file [Issue384Test.zip](https://github.com/FasterXML/jackson-dataformat-xml/files/4280376/Issue384Test.zip) containing :
* The generated class without the workaround annotation : `StatsQueryNoWorkaround`
* The generated class with the workaround annotation : `StatsQueryWithWorkaround`
* A Junit5 test class showing that with the same test, it passes only with the workaround
* a pom file if you want to test directly with maven
* an iml file for IntelliJ


Essentially, if you compare the class, you can see that the generated code does not add
`@JsonProperty` on the constructor of the class and its builder.
Without internal knowledge of Jackson, I don't know if it's a Jackson bug (or missed use case) or if Lombok shall have transferred the xml property (I suppose it can't; though, because Lombok is not supposed to be aware of Jackson special annotation, i.e. `@JacksonXmlProperty`).

**Comment by Bokoblin** [comment] 2020-03-05 08:44
@cowtowncoder Thank you, hope you'll find the time too

What do you mean concerning JDKs differencies, isn't jackson based on Java 8 or newer?

**Comment by cowtowncoder** [comment] 2020-03-05 18:40
@Bokoblin Jackson can run on JDK6 and above (most, but not all components), and thereby there are Java 7 users at least. This is the reason why extensions that rely on Java 8 features (such as method/constructor parameters names) exist as modules. Jackson 3.0 has Java 8 as baseline and this division will disappear.
But as I mentioned, it is also important to ensure that `javac` is configured to include parameter names in bytecode, even when using JDK 8 (not sure if that is optional for later JDKs or not).

**Comment by Bokoblin** [comment] 2020-03-06 07:49
Okay, I see.
Do you think version 3.0 might already have fixed that or you were just speaking generally?

What do you mean by javac must be configured to include parameter? Is this something I must enable on my project or is it Jackson related ?

**Comment by cowtowncoder** [comment] 2020-03-06 17:50
I may have over-described details of why annotations are sometimes needed, for specific case of constructor parameters. Diff between Jackson 2.x and 3.0 is not all that pertinent here; problem almost certainly still exists with 3.0 too.

As to javac: it has nothing to do with Jackson, general setting. I think inclusion is enabled by default, but some IDEs have/had it disabled, leading to weird test failures some users reported.

**Comment by Bokoblin** [comment] 2020-03-06 22:03
In any case, I have re-read the messages, and actually the issue isn't related to the parameter names you mentioned. Because in case my xml property is "phone-number" for example (I have some hyphen parameters in my lib), we can't put a pojo hyphen based parameter

**Comment by cowtowncoder** [comment] 2020-03-07 00:33
Right, my bad at extending on parts that are not immediately relevant here.

**Comment by janrieke** [comment] 2020-04-06 11:45
I just stumbled upon this when trying to solve [this StackOverflow question](https://stackoverflow.com/questions/61037425/how-to-deserialize-java-optional-field-with-lombok-builder).

1. Lombok does not automatically copy over `@JacksonXmlProperty` to the builder's setter methods. You have to configure that.
2. Even if you do, Jackson does not recognize that annotation. I think the reason is that lombok puts it on the parameter. If you manually write your builder and put the annotation on the builder's _setter method_, it works.

This is confusing, because the `@JsonProperty` works on the parameter as well as on the method.

**Comment by Bokoblin** [comment] 2020-04-06 13:24
@janrieke For a recent version of my library, that I implemented last week I needed also Json serialization so I ended up putting `JsonProperty` on every fields (as not doing so causes a serialization of my classes to the empty object `{}`).

```If you manually write your builder and put the annotation on the builder's setter method, it works```
=> Actually, if things were fully working out of the box between Lombok and Jackson, I would not need to bloat my code with a custom builder, I need it because Jackson deserialization does not set default field values (at least if @Builder.default annotation is present) so they are set to null.

If I have time, I may check if the StackOverflow question you mention could simplify my code, but I think waiting for Jackson 3.0 should be a better idea instead of hacking around as the latter is built on Java 8 ^^

**Comment by janrieke** [comment] 2020-04-06 19:51
FYI: I created a PR for lombok (rzwitserloot/lombok#2416 ) to also automatically copy `@JacksonXmlProperty` to the builder setter method (as it already does for `@JsonProperty`).

**Comment by cowtowncoder** [comment] 2020-05-23 21:17
One quick note: `@JsonProperty` and `@JacksonXmlProperty` have never been allowed, nor are intended to be allowed, on setter method parameter. This is not how they are designed to work -- they are to be added on method (or field); with exception of Constructor/factory method arguments (as there are often multiple ones).
This is not a new limit and has been the case for now 15 years so I am bit puzzled why anyone would expect them to work on setter arguments.

I am not against adding something in javadocs per se, just surprised that this is not clear from all existing code and documentation.

**Comment by cowtowncoder** [comment] 2020-05-23 21:47
Ok. So the original issue is that user assumes that the annotations on value class would be used by the builder: this is not the case -- annotations must be on value class. In fact, annotations on value class are all ignored, except for one that direct builder to use.

Change to this behavior has been requested, but would need to be in `jackson-databind`, not in XML module (annotations should be associated).

Although in case of Lombok and similar tools/frameworks, they can (and need to) copy relevant annotations -- in these cases user has no access.

Will close this issue as I do not think XML module can actually do anything about it.

**Closed by cowtowncoder** 2020-05-23 21:47 UTC

**Comment by Bokoblin** [comment] 2020-05-23 21:56
I acknowledge your final answer. Should I open a ticket in the relevant repository to track this request?

**Comment by cowtowncoder** [comment] 2020-05-24 17:22
It would make to see if you can see something that matches. There are, for example:

* https://github.com/FasterXML/jackson-databind/issues/2712 - use `@JsonNaming` from value class for builder
* https://github.com/FasterXML/jackson-databind/issues/2391 - use (all kinds of?) annotations, including ones on properties

so I am bit torn on exactly how to formulate RFE. It sounds like this would be more complicated than just associating class-annotations from value type to builder (which is relatively easier), and somehow tried to associate annotations on properties to help guide builder.

So I guess, yes, please file a `jackson-databind` request: it can be referring to `@JsonProperty` (but mentioned `@JacksonXmlProperty` as alias) since main mechanism would be about inclusion, naming.
