### ISSUE TITLE
failed to deserialize all interleaved elements for list

### ISSUE THREAD

**Issue by WangJiannan** [FasterXML/jackson-dataformat-xml#165] opened 2015-10-28 16:19 UTC
POJO:

``` java
@JacksonXmlRootElement(localName = "a")
public class A {
    public static class B {
        @JacksonXmlProperty(localName = "id")
        public String id;
    }

    @JacksonXmlProperty(localName = "b")
    @JacksonXmlElementWrapper(useWrapping = false)
    public List<B> bList;
}
```

XML:

``` xml
<a>
   <b><id>id1</id></b>
   <any-tag/>
   <b><id>id2</id></b>
</a>
```

It's expected to get two elements 'id1' and 'id2' in bList, but only 'id2' is available after deserialisation.

related links:
- http://stackoverflow.com/questions/29087335/fasterxml-jackson-dataformat-xml-deserialize-mixed-ordered-tag
- http://jackson-users.ning.com/forum/topics/parsing-xml-nodes-in-mixed-order

**Comment by cowtowncoder** [comment] 2015-10-28 17:44
Please include Java POJOs included, as well as code. XML structure itself is not enough to know what exactly you are trying to do.

Please also note that reading of root-level `List`s (that is, trying to directly read `List` or `Collection`) values is not a supported use case.

**Comment by WangJiannan** [comment] 2015-10-29 02:31
Sorry, I didn't state clearly. The description is updated and it's not the root-level List issue.

Actually, I find the [second link](http://jackson-users.ning.com/forum/topics/parsing-xml-nodes-in-mixed-order) is replied from you, so it seems you already know this issue. Would you consider to fix it?

**Comment by cowtowncoder** [comment] 2015-10-29 03:08
Thank you for the update.

The problem here is the `<any-tag/>`. Since it is in the middle of expected list of entries, it will break handling. I do not think this use case can be supported, unfortunately.

**Comment by WangJiannan** [comment] 2015-10-29 06:32
I think it's a very common use case when editing XML manually by many people. Nobody is willing to take care of tags order.
Is it a technical problem under Jackson framework or XML spec defines the behaviour?

**Comment by cowtowncoder** [comment] 2015-11-04 00:51
It is a limitation by Jackson module. XML allows any sequence of tags, repeating, and so forth.
I do not know if JAXB implementations would, for example, handle this.

**Comment by pswulius** [comment] 2017-03-15 23:44
I ran into this issue parsing SVG documents.  Polygons, paths, and rects are interleaved.  Anyone know if there is any jackson solution at this time?

**Comment by cowtowncoder** [comment] 2017-03-15 23:55
@pswulius one thing that 2.9 will add in `jackson-databind` is `@JsonMerge` like so:

```java
public class Container {
   @JsonMerge(OptBoolean.TRUE)
   public List<Point> points = new ArrayList<>();
}
```

which would not reset value, so multiple segments would effectively be merged.
I have not tried that with XML module but in theory it should work.
Before 2.9 you could still add "setPoints(List<> p) { }" method that similarly appends entries, but that is bit more intrusive.

This assuming that problem is not due to mixed content (that is, no unwrapped text/cdata sections), but due to disjoint sequences of elements with same name.

**Comment by pswulius** [comment] 2017-03-16 18:54
Excellent.  Thank you for the upcoming feature, and the current workaround.  Both are great, and I've confirmed the setPoints(List<> p) workaround.  Thank you for pointing that out!

**Comment by cowtowncoder** [comment] 2020-05-20 20:25
Since there is a work-around (or two) but no clear path on how to solve this in other ways, will close the issue: should be possible for users to find work-arounds on closed issue.

**Closed by cowtowncoder** 2020-05-20 20:25 UTC
