### ISSUE TITLE
`MismatchedInputException` encountered while deserializing XML to an Enum type using a factory method

### ISSUE THREAD

**Issue by WannabeSoftwareEngineer** [FasterXML/jackson-dataformat-xml#682] opened 2024-11-07 12:33 UTC
Hello,
I'm trying to serialize an Enum type to XML, then read it back, but I get an input mismatch error related to JsonCreator. 

Could someone provide insights into why deserialization fails? 

Any help would is appreciated. Thank you.

Error
```java
com.fasterxml.jackson.databind.exc.MismatchedInputException: Input mismatch reading Enum `com.xxx.yyy.Country`: properties-based `@JsonCreator` ([method com.xxx.yyy.Country#fromValue(java.lang.String)]) expects String Value, got Object value (`JsonToken.START_OBJECT`)
```

Test
```java
@Test
void aTest() throws JsonProcessingException {
    XmlMapper xmlMapper = new XmlMapper();
    
    String s = xmlMapper.writeValueAsString(Country.ITALY);
    assertThat(s).isEqualTo("<Country>Italy</Country>");
    
    Country country = xmlMapper.readValue(s, Country.class);
    assertThat(country).isEqualTo(Country.ITALY); // fails with the error reported above
}
```

Country.java
```java
public enum Country {
    ITALY("Italy"),
    NETHERLANDS("Netherlands");

    private String value;

    Country(String value) {
        this.value = value;
    }

    @JsonValue
    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static Country fromValue(String value) {
        for (Country b : Country.values()) {
            if (b.value.equals(value)) {
                return b;
            }
        }
        throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
}
```

library: `com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.17.1`

original report submitted here: https://groups.google.com/g/jackson-user/c/xXgyb_uKbGg/m/fCcNz9WOCAAJ

**Comment by pjfanning** [comment] 2024-11-07 13:41
Another issue with a similar `JsonCreator` annotation - https://github.com/FasterXML/jackson-databind/issues/4785

**Comment by cowtowncoder** [comment] 2024-11-07 20:02
Probably not same root cause, but good to reference nonetheless. That one seems like invalid issue (but understandable; 2.18 changing behavior but in this case -- seems to me -- fixing it).

**Comment by cowtowncoder** [comment] 2024-11-09 01:27
Note to self: jackson-databind `EnumDeserializer` has handling in

```
    @Override
    public Object deserialize(JsonParser p, DeserializationContext ctxt) throws IOException
    {
         // ....
        if (p.hasToken(JsonToken.VALUE_STRING)) {
            return _fromString(p, ctxt, p.getText());
        }
         // ....
        // 29-Jun-2020, tatu: New! "Scalar from Object" (mostly for XML)
        if (p.isExpectedStartObjectToken()) {
            return _fromString(p, ctxt,
                    ctxt.extractScalarFromObject(p, this, _valueClass));
        } 
    }
```

which handles special XML-ness aspects. But this is probably not handled for factory case, for some reason.

**Comment by WannabeSoftwareEngineer** [comment] 2024-11-20 14:14
Do you have any suggestions for a workaround or where I should be looking at to check if I can add one temporary?
At the moment, we can't change the type, e.g. Country.java, because it is auto-generated and we can't change the template without undertaking a massive refactoring of our codebase.

**Comment by cowtowncoder** [comment] 2024-11-22 20:35
@WannabeSoftwareEngineer No, unfortunately I can't think of an obvious work-around here.

**Comment by cowtowncoder** [comment] 2024-11-25 00:26
Fixed via https://github.com/FasterXML/jackson-databind/issues/4807 (and added tests to verify via #685). Will be in 2.18.2.

**Closed by cowtowncoder** 2024-11-25 00:26 UTC
Labels: 2.18
