### ISSUE TITLE
Deserialization with XmlMapper and DeserializationFeature.UNWRAP_ROOT_VALUE no longer works in 2.12

### ISSUE THREAD

**Issue by ionel-sirbu-crunch** [FasterXML/jackson-dataformat-xml#485] opened 2021-07-16 13:19 UTC
I've recently updated a project at work to Spring-boot 2.5.2 & one of the tests started failing. As it turns out, the root cause lies in the deserialisation of XML data.
We use the root unwrapping feature & have the data model class annotated with `@JsonRootName`.

I've created a very simple project to give you an example of our usage [here](https://github.com/ionel-sirbu-crunch/fasterxml-unwrap-test).

Old, working version: 2.11.4
New, non-working version: **2.12.3**

Any advice is much appreciated.
Thanks!

**Comment by cowtowncoder** [comment] 2021-08-30 00:41
This was not known to be a use case; no tests covering it. Unless I misunderstand usage, it was not supported to begin with -- and was confusing for users since serialization and deserialization for XML were asymmetric: things simply would not work if you serialized something, then tried to read it back.
And since Jackson XML modules stated goal is to specifically "read what it writes": that is, round-tripping in that way is the main goal, older behavior still seems wrong, fundamentally.

This was not reported as an issue during Jackson 2.12 release candidate phase, as far as I know, meaning that 2.12.0 was released with the change as intended.

But if and when it turns out there is existing usage I do want to figure out how to resolve that, for 2.13. 2.12 is something we can do little about because its API is fixed (no additions) and since behavior of .0 was changed purposefully.

I am a little bit hesitant to try to undo change and allow `UNWRAP_ROOT_VALUE`, given the noted problems.
I could instead include a new feature -- `ToXmlGenerator.Feature.XXX` -- although that also seems a bit redundant.

**Comment by marcospassos** [comment] 2021-08-30 14:59
We'll try to adjust on our side to not bring more maintenance for something that isn't officially supported. So, for us, no need to spend time on this.

**Comment by cowtowncoder** [comment] 2021-08-30 22:32
@marcospassos I appreciate your flexibility and am sorry there was this breakage. I will still consider revert here; I simply did not realize the feature was used (and considered useful) on XML side.

**Comment by ionel-sirbu-crunch** [comment] 2021-08-31 08:55
@cowtowncoder Thanks for looking into this! As I mentioned in the initial description, we only _deserialize_ the XML data (it comes from an external service), so I wasn't aware of the asymmetry of the `UNWRAP_ROOT_VALUE` feature.
For us this is no longer a matter of urgency though, as I've already implemented a workaround. Luckily for us, the root element has the same shape every time, so it was easy to work around it.

Should you decide to leave this feature as it is, may I suggest adding a matrix of unsupported `ObjectMapper` features to the readme so that it's a little more transparent to the developers what they can & cannot use?

Many thanks!

**Comment by cowtowncoder** [comment] 2021-09-04 01:05
@ionel-sirbu-crunch I fully agree!

Looking at code change(s) involved, I think I can do a revert here, but I am thinking that I will want to add some additional switch on XML module itself.

Regardless, I think the idea of mentioning complications for `UNWRAP_ROOT_VALUE` is valid to note in core jackson-databind Javadocs.

**Closed** 2021-09-19 00:45 UTC

**Comment by cowtowncoder** [comment] 2021-09-19 00:58
Created #494 for possible follow-up work.
