### ISSUE TITLE
XML Deserialization error when attribute's name equals children elements' name

### ISSUE THREAD

**Issue by qdoot** [FasterXML/jackson-dataformat-xml#335] opened 2019-03-12 10:19 UTC
As the title says, I'm having a struggle trying to deserialize the following XML:

`<root>
   <txt occ="1">
      <occ id="1">first element</occ>
      <occ id="2">second element</occ>
   </txt>
   <txt occ="2">
      <occ id="1">first element</occ>
      <occ id="2">second element</occ>
   </txt>
</root>`

Because the tag "txt" has an attribute "occ" which is the same name used for the children elements of "txt".

Changing the name (either of the attribute, as shown below, or of the children elements) makes it work like a charm:

`<root>
   <txt occ_attr="1">
      <occ id="1">first element</occ>
      <occ id="2">second element</occ>
   </txt>
   <txt occ_attr="2">
      <occ id="1">first element</occ>
      <occ id="2">second element</occ>
   </txt>
</root>`

And this is how I set up my XmlMapper:

`XmlMapper xmlMapper = new XmlMapper();
xmlMapper.registerModule(new JaxbAnnotationModule());
xmlMapper.setSerializationInclusion(Include.NON_NULL);
xmlMapper.configure(SerializationFeature.WRAP_ROOT_VALUE, false);
xmlMapper.configure(SerializationFeature.WRITE_EMPTY_JSON_ARRAYS, false);`

Using v.2.7.9

**Comment by cowtowncoder** [comment] 2019-04-05 22:03
Ok, not quite sure what the intended suggested problem/change is -- true, it is not legal to have same name for both attribute and element within same document. That will not work for databinding.

**Comment by qdoot** [comment] 2019-04-27 16:14
Well, sounds like a bug to me.

**Comment by cowtowncoder** [comment] 2020-05-23 21:54
Not a bug, implementation limitation: use case is not supported.
Ideally it would be, but it is unclear to me how this would even work with POJOs where property names must be unique.
The main approach I suppose would be to quietly ignore attribute altogether.

Still, element-vs-attribute name collision with bit clearer semantics has been reported as #65 so I will close this as a dup and any improvement would be applicable for both cases.

**Closed by cowtowncoder** 2020-05-23 21:54 UTC
Labels: name-collision
