### ISSUE TITLE
All attributes after xsi:nil is ignored

### ISSUE THREAD

**Issue by o3661606** [FasterXML/jackson-dataformat-xml#385] opened 2020-03-01 16:05 UTC
Version: 2.10.2

The order of `xsi:nil` will affect the parsing result.

All fields of 1st `<item>` object will be `null` (seems parsing will stop once found `xsi:nil`?) 
In 2nd & 3rd `<item>`,  only `getValue()` will return `null`

XML
```
<items xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" >
  <item xsi:nil="true" attr1="a" type="est" idx="1" />
  <item attr1="b" type="est" idx="2" xsi:nil="true"/>
  <item attr1="c" type="est" idx="3" xsi:nil="true"/>
</items>
```

POJO
```
public class Item {
  private String attr1;
  private String type;
  private String idx;
  @JacksonXmlText
  private String value;
  // ..getter and setter
}
```

**Comment by cowtowncoder** [comment] 2020-03-02 02:17
Could you show this in form of a unit test? I do not doubt there is an issue (which I think is not only due to ordering, but also existence of multiple other attributes), but it would be good to easily reproduce it and verify fix for the problem.

**Comment by o3661606** [comment] 2020-03-02 05:53
Created a unit test

https://gist.github.com/o3661606/4d55999b0bced2eca034a97d7e55c6f5

**Comment by o3661606** [comment] 2020-03-02 19:40
It seems once `_xsiNilFound` is true, `_skipUntilTag()` will skip until `END_ELEMENT`

https://github.com/FasterXML/jackson-dataformat-xml/blame/master/src/main/java/com/fasterxml/jackson/dataformat/xml/deser/XmlTokenStream.java#L341

**Comment by cowtowncoder** [comment] 2020-05-13 21:57
Hmmh. My assumption so far was that if `xsi:nil` is set, then element simply represents `null`, and no more information is to be gained there, including other attributes. I am actually not sure what would be expected semantics here otherwise -- why is that marker used, if entity is not something that does not exist? Where would attribute values be used?

So I am kind of curious as to intended semantics here: something is off with the model.

**Comment by cowtowncoder** [comment] 2020-11-14 00:20
I think handling is as expected: `xsi:nil` is marker for "annotated" element to be considered `null` for all practical purposes.

I would be open for adding a `FromXmlParser` feature to disable such handling, if that makes sense -- but for now closing this as "works as intended". New issues are fine, if outlining desired changes.

**Closed by cowtowncoder** 2020-11-14 00:20 UTC
