### ISSUE TITLE
Deserialization if an empty list (with empty XML tag) results in `null`

### ISSUE THREAD

**Issue by danblack** [FasterXML/jackson-dataformat-xml#124] opened 2014-11-08 19:14 UTC
XML serialization/deserialization of an empty array is not working consistently (unlike JSON) .
When I try to deserialize an empty list from xml I get a null list (but I except to get an empty list).  
I don't have this problem with JSON.

Library version 2.4.3, jdk 8.0_25
Here is my example

``` java
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.dataformat.xml.XmlMapper;
import com.fasterxml.jackson.module.jaxb.JaxbAnnotationModule;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

public class Test {

    @XmlRootElement(name = "root")
    public static class TestList {
        @XmlElement(name = "list")
        public List<Object> list;
    }

    public static void main(String[] args) throws IOException {
        // XML
        XmlMapper xmlMapper = new XmlMapper();
        xmlMapper.registerModule(new JaxbAnnotationModule());
        TestList originalObject = new TestList();
        originalObject.list = new ArrayList<Object>();
        String xml = xmlMapper.writeValueAsString(originalObject);
        System.out.println(xml); // print <root xmlns=""><list></list></root>
        TestList actualObject = xmlMapper.readValue(xml, TestList.class);
        System.out.println(actualObject.list);  // print null

        // JSON
        ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.registerModule(new JaxbAnnotationModule());
        String json = objectMapper.writeValueAsString(originalObject);
        System.out.println(json); // print {"list":[]}
         actualObject = objectMapper.readValue(json, TestList.class);
        System.out.println(actualObject.list); // print []
    }
}
```

**Comment by loki2302** [comment] 2015-01-21 10:04
Just faced the same issue. Are there any plans to make this behavior configurable?

**Comment by cowtowncoder** [comment] 2015-01-21 20:49
At first I'd need to understand what the problem is: most likely it is due to convoluted way XML stream is read, to try to determine whether an element would be considered equivalent to JSON Object or Array.

Another thing to try to is to see if 2.5.0 makes any difference; there was at least one fix related to List/array handling.

**Comment by loki2302** [comment] 2015-01-22 07:11
Just tried 2.5.0:

    @Test
    public void canDeserializeEmptyCollection() throws IOException {
        String xml =
                "<PersonList>" +
                    "<people />" +
                "</PersonList>";

        XmlMapper xmlMapper = new XmlMapper();
        PersonList personList = xmlMapper.readValue(xml, PersonList.class);
        assertNotNull(personList.people); // <--- HERE
        assertEquals(0, personList.people.size());
    }

    public static class PersonList {
        @JacksonXmlElementWrapper(localName = "people")
        @JacksonXmlProperty(localName = "person")
        public List<Person> people;
    }

    public static class Person {
        public String name;
    }

`personList.people` is still `null`.

**Comment by cowtowncoder** [comment] 2015-01-22 08:02
Thank you for verifying this.

So, it is a bug, not an intentional deviation from JSON handling.

**Comment by avianey** [comment] 2015-10-21 07:34
any new on this, still the same issue in the latest jackson release...

**Comment by ilgrosso** [comment] 2015-11-23 15:48
Just verified with 2.6.3 - still the same...

**Comment by rajeshksv** [comment] 2016-03-09 05:14
Any update on the same ?

**Comment by cowtowncoder** [comment] 2016-03-09 05:20
No news here.

**Comment by kmp3325** [comment] 2016-06-10 21:24
Just ran into this problem myself...If you reverse the annotations it seems to work without issue:

```
    @JacksonXmlElementWrapper(localName = "person")
    @JacksonXmlProperty(localName = "people")
    public List<Person> people;
```

**Comment by cowtowncoder** [comment] 2016-06-11 01:59
Yes, I can reproduce this now. Whether empty element is expressed as `<list/>` or `<list></list>` makes no difference, and having white space (`<list>    </list>`) actually produces an error since white space is expressed as String token (which it could be).

**Comment by ssmoss** [comment] 2016-10-18 18:16
Just curious if there is any ETA on a fix for this? Thanks.

**Comment by lightbringer** [comment] 2017-06-29 19:37
My workaround in 2.8.9 was a readResolve method that checks if any of the collections in the class were null and respectively created a new collection.

**Comment by newtechfellas** [comment] 2018-03-23 16:12
Any solution to this?  I see the same problem. I upgraded from 2.1.1 to 2.6.7. 2.1.1 was working. upgrade broke the tests while deserializing empty xml element into a array list property

**Comment by mykmaley** [comment] 2018-11-01 16:11
Still suffering with this bug in 2.8.10.  Any ETA?  Unclear why this is closed since it's still occurring.

**Comment by mschne** [comment] 2019-02-08 09:51
We also encountered this problem in our project. While trying to fix this i noticed that there is a feature FromXmlParser.Feature.EMPTY_ELEMENT_AS_NULL which is enabled by default. I tried to disable it but it did not make any difference in the above testcase. 
```
XmlMapper xmlMapper = new XmlMapper();
xmlMapper.disable(FromXmlParser.Feature.EMPTY_ELEMENT_AS_NULL);
```
Is this feature related to this problem? How can we make it work?

**Comment by KainWhite** [comment] 2019-11-05 15:39
Still this same issue in 2.10.0. Maybe someday...

**Comment by henrik242** [comment] 2020-01-13 15:06
This might be fixed in 2.10.2 after this fix: https://github.com/FasterXML/jackson-dataformat-xml/issues/378

**Comment by cowtowncoder** [comment] 2020-01-15 00:01
@henrik242 Unfortunately that is bit different problem. 

However! There is actually a way to make it work by using (relatively) new "config overrides" with null-handling override. Specifically, adding this:

```
       xmlMapper.configOverride(List.class)
            .setSetterInfo(JsonSetter.Value.forValueNulls(Nulls.AS_EMPTY));
```

will then convert logical `null` value into "empty", and for `List`s that would be empty `List`.

**Comment by cowtowncoder** [comment] 2020-06-06 02:41
Fixed for 2.12.0

**Closed** 2020-06-06 02:41 UTC

**Comment by henrik242** [comment] 2020-10-13 09:26
Issue #427 might be related to this

**Comment by henrik242** [comment] 2021-01-18 12:18
This is still a problem in 2.12.1

**Comment by cowtowncoder** [comment] 2021-01-18 18:54
@henrik242  If there is a remaining problem with this issue on 2.12.1, reproducible with just this module (there are some issues related to Kotlin module which gets trickier), could you please file a new issue with reproduction?
I usually do not reopen old issue if (assumed) fix has been released in a production version as that complicates release notes.

**Comment by henrik242** [comment] 2021-01-19 09:30
@cowtowncoder I've only managed to reproduce it with the kotlin and xml module together.   So I'll just stick with https://github.com/FasterXML/jackson-module-kotlin/issues/396 :)
